### ISSUE TITLE
Question regarding algorithm

### ISSUE THREAD

**Issue by ryanhz** [G6EJD/ESP32-Morse-Decoder#3]
Hi @G6EJD 

Thank you for your sharing code, you are awesome.

I tried to follow your code's algorithm, but coundn't understand the mathematical algorithm behind the code.

What is the meaning of k and omega below?
```
  float omega;
  k = (int) (0.5 + ((n * target_freq) / sampling_freq));
  omega = (2.0 * PI * k) / n;
  sine = sin(omega);
  cosine = cos(omega);
  coeff = 2.0 * cosine;
```

**Comment by G6EJD** [comment]
K is from the electrical expression of 2.PI.F (2 x PI x Frequency)
So really I should have used F instead of K
Omega is merely an angle in degrees to be used in mathematical expressions like SIN(omega)  COS(omega), etc.
That section of code determines the size/amplitude of the tone

**Comment by ryanhz** [comment]
Thank you for your reply.

So 2.PI.F is the angular frequency of frequency F = (int) (0.5 + ((n * target_freq) / sampling_freq));
plus 0.5 is for rounding. but what does `(n * target_freq) / sampling_freq)` mean?
And what does omega = (2.0 * PI * F) / n means, which is the angular frequency/n

I can't find the math behind it.

**Comment by G6EJD** [comment]
It’s an FFT there are many techniques you can implement also the Arduino FFT could have been used, but see here for the full mathematical analysis:
https://en.wikipedia.org/wiki/Goertzel_algorithm

**Comment by ryanhz** [comment]
Oh, cool, thank you for the link.

I was thinking using hardware to detect the envelope of AM signal then count how long the high and low.

**Comment by G6EJD** [comment]
Hardware will of course give you more code time, but with the ESP32 you’ve got plenty of time to spare, so may as well use a software technique, decoding the audio to tone or no-tone is relatively easy, it’s the task of determining dit-dah lengths with spacing and then the variability of hand keying.

**Comment by ryanhz** [comment]
Yes, you are right. Software is more flexible.
I failed to decode anything using the microphone module.  I end up feed the audio output directly to the ADC input with DC bias, so there is noise. But still there are some error decoding.

**Comment by ryanhz** [comment]
The decoded message in the sampe morse code audio is:

`now is the time for all good men to tnome to the aid of the parttm. 0123456789ft<<t,/ ie quick brown fodt jumps over the lazy dogs back.`

**Comment by G6EJD** [comment]
The microphone modules are ok, some are AC coupled some not, some have a DC offset potentiometer which ideally is used to adjust the output offset to the middle of the ADC input range about 1.5volts, or AC couple it with a capacitor and then use a DC offset on the ADC I out comprised of two relatively high value resistors say 3.3—100K—-ADC—-100K—-Gnd and then connected AC coupled audio to the ADC now the ADC input will be varied around the 1.5v region. The software is looking for excursions and the FFT will remove the DC component. The best way of testing, if you can is to send it on/off tones of a known frequency (morse speed) then you can examine what your values are doing and where it’s going wrong. Real morse on HF is exceptionally noisy a d why I never used off-air audio for my demo! 
filtering is always going to be required which is why selecting CW on an HF transceiver or receiver will usually introduce a very narrow filter usually with a bandwidth of 100/150Hz so exceptionally narrow then you get good performance. The human ear is very good at filtering.
If you feed the FFT with a wide band signal it will sample and take a composite of all the audio pass band, only the dominant audio will prevail in the sampling but if you have two tones at that instance say the Norse tone and a noise spike then the two compete so what you can do is to concentrate the analysis of the FFT in the frequency domain and only inspect the frequency let’s call it bucket for that value that’s a form of digital filtering, if you see my ESP32 spectrum analyser you can see the FFT code there each array index gives the amplitude of the incoming frequency so array position (depending on sampling g setting) 100 will be 400Hz, 101 410Hz and so on, therefore by monitoring just say 0 and 100 array positions you can tell if there is 300Hz Norse tone or not

**Comment by ryanhz** [comment]
```3.3—100K—-ADC—-100K—-Gnd and then connected AC coupled audio to the ADC now the ADC input will be varied around the 1.5v region```
That is what I did without the microphone module. The ADC input has a good dynamic range from about 0V to about 3V, maybe some components to limit the input in case the input audio is too loud.

**Comment by vinloren** [comment]
Nice project of yours, I was thinking of using ESP32 to develop a RTTY decoder. Could your approach be modified to support RTTY receiving or it is a crazy idea not feasible? I'd like to have some hint.. Thanks and regards Vincenzo

**Comment by G6EJD** [comment]
Not a crazy idea at all. In fact there are FFT RTTY decoders around, try search google with 'Arduino RTTY FFT'
Example: https://forum.arduino.cc/t/arduino-rtty-decoder/82177
Unfortunately the on-board UART does not support 5-bit data and can't be set to 45.5 buad for RTTY but doing this in software solves that problem.

**Comment by vinloren** [comment]
Thanks a lot for the hint.
